### ISSUE TITLE
After installation and user created Error happens

### ISSUE THREAD

**Issue by barisakpunar** [ninianne98/CarrotCakeCMS-MVC#2] opened 2016-01-11 12:40 UTC
After installation and user created "Server cannot append header after HTTP headers have been sent." error happens at SiteInfo.cshtml line 26

@Html.AntiForgeryToken()

**Comment by ninianne98** [comment] 2016-01-11 13:23
just hit continue, I was only ever able to reproduce it before changing from a response.redirect to an actionresult.  it's because of the test performed when trying to access an admin screen and since there is no site yet, it redirects to the site creation screen.  I'll look into seeing if I can force it to trigger on my end with an empty DB, bit I'm not sure why my IDE no longer gives me the error.

**Comment by ninianne98** [comment] 2016-01-11 14:01
I just checked in a minor change in the redirect, I was able to force the issue, and then make it go away, hopefully it will clear the issue. but note that this is an issue that can safely be continued past.

**Comment by barisakpunar** [comment] 2016-01-11 15:09
Now After I logged in Browser gives this error

This webpage has a redirect loop

ERR_TOO_MANY_REDIRECTS

**Comment by ninianne98** [comment] 2016-01-11 15:14
what browser?  I've been using FF 40 and running under debugger and created several new sites with no issue.  Were you able to create the first user?  Were you able to login and at that point encountered the issue?  Was it after creating the site profile? I've been able to login and logout several times on existing sites both in debugger and on IIS with no issues.

**Comment by barisakpunar** [comment] 2016-01-11 15:29
I tried both FF and Chrome. The first user is created. 
After home Page I go to the "http://localhost:10109/c3-admin/SiteInfo" as directed.
That is where the loop happens

**Comment by ninianne98** [comment] 2016-01-11 16:00
Ah, I'd be willing to bet you didn't start over with a fresh database when you ran into the case sensitivity issue.  Because of that, it wasn't able to record the version key. check the table [carrot_DataInfo] - I bet it doesn't have any records in it.  Add key "DBSchema" and value "20151001" to it.

You should also get 167 rows if you run this SQL:
SELECT *
  FROM [INFORMATION_SCHEMA].[COLUMNS]
  WHERE [TABLE_NAME] like 'carrot%'
    OR [TABLE_NAME] like 'membership%'

since you appear to be running in visual studio, what does the error stack look like in the carrot_errors.txt around the time of the error?

**Comment by barisakpunar** [comment] 2016-01-11 16:33
I found the problem.

Since VS Settings Language is Turkish. ToLower() method returns "siteınfo" instead of "siteinfo"

We should change two lines in CmsAdminController.cs

   string action = vals["action"].ToString().ToLower();
  string controller = vals["controller"].ToString().ToLower();

to 

  string action = vals["action"].ToString().ToLowerInvariant();
  string controller = vals["controller"].ToString().ToLowerInvariant();

Thank you for your concern.

**Comment by ninianne98** [comment] 2016-01-11 17:25
good detective work! I'll get the change in in the next day or so.

**Comment by ninianne98** [comment] 2016-01-12 14:46
Just made a commit which includes a mass conversion to use ToLowerInvariant/ToUpperInvariant

**Comment by ninianne98** [comment] 2016-01-14 06:38
I'm going to go ahead and close this.  if you run into another regionalization issue, just open another issue and provide steps and any research you've done on your own.

**Closed as completed by ninianne98** 2016-01-14 06:38 UTC
Labels: enhancement
